/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.mercadopaodesal.ui;

import io.mercadopaodesal.dao.NF;
import io.mercadopaodesal.dao.NFDAO;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class NfScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NfScreen.class.getName());

    /**
     * Creates new form NfScreen
     */
    public NfScreen() {
        initComponents();
        configurarData();
    }
    
    private void configurarData() {
        date_field.setText("yyyy-mm-dd");
        date_field.setForeground(Color.GRAY);

        date_field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (date_field.getText().equals("yyyy-mm-dd")) {
                    date_field.setText("");
                    date_field.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (date_field.getText().isEmpty()) {
                    date_field.setText("yyyy-mm-dd");
                    date_field.setForeground(Color.GRAY);
                }
            }
        });
    }
    
    private void addNF() {
        NF newNF = new NF();

        // Only parse ID if not blank
        String idText = id_field.getText().trim();
        if (!idText.isEmpty()) {
            try {
                newNF.setId(Integer.parseInt(idText));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID inválido.");
                return;
            }
        }

        newNF.setDate(date_field.getText());

        try {
            newNF.settValue(Double.parseDouble(tValue_field.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor total inválido.");
            return;
        }

        String clientIdText = clientId_field.getText().trim();

        if (costumer_option.isSelected()) {
            if (!clientIdText.isEmpty()) {
                newNF.setCustomerID(Integer.parseInt(clientIdText));
                newNF.setSuplierID(null);
            } else {
                JOptionPane.showMessageDialog(this, "ID do Cliente está vazio.");
                return;
            }
        } else if (suplier_option.isSelected()) {
            if (!clientIdText.isEmpty()) {
                newNF.setCustomerID(null);
                newNF.setSuplierID(Integer.parseInt(clientIdText));
            } else {
                JOptionPane.showMessageDialog(this, "ID do Fornecedor está vazio.");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione Cliente ou Fornecedor.");
            return;
        }

        NFDAO sDao = new NFDAO();
        sDao.add(newNF);

        clearForm();
        System.out.println("addNF executado com sucesso");
    }

    
    private void updateNF (){
        NF newNF = new NF();

        newNF.setId(Integer.parseInt(id_field.getText()));
        newNF.setDate(date_field.getText());
        newNF.settValue(Double.parseDouble(tValue_field.getText()));
        if(costumer_option.isSelected()){;
            newNF.setCustomerID(Integer.parseInt(clientId_field.getText()));
            newNF.setSuplierID(0);
        }else{
            newNF.setCustomerID(0);
            newNF.setSuplierID(Integer.parseInt(clientId_field.getText()));
        }

        NFDAO cDAO = new NFDAO();
        cDAO.update(newNF);

        clearForm();

        System.out.println("editCustomer escolhida");
    }
    
    private void clearForm(){
        id_field.setText("");
        tValue_field.setText("");
        buttonGroup1.clearSelection();
        clientId_field.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        idSrch_field = new javax.swing.JTextField();
        srch_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id_field = new javax.swing.JTextField();
        Data = new javax.swing.JLabel();
        date_field = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        tValue_field = new javax.swing.JTextField();
        suplier_option = new javax.swing.JRadioButton();
        costumer_option = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clientId_field = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        clearId = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        srch_btn.setText("Buscar");

        jLabel2.setText("ID");

        id_field.setEnabled(false);

        Data.setText("Data");

        date_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-mm-dd"))));
        date_field.setToolTipText("");
        date_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_fieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor total");

        buttonGroup1.add(suplier_option);
        suplier_option.setText("Fornecedor");

        buttonGroup1.add(costumer_option);
        costumer_option.setText("Cliente");
        costumer_option.setToolTipText("");

        jLabel4.setText("Nota para: ");

        jLabel5.setText("ID cliente/fornecedor");

        save_btn.setText("Atualizar");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        clearId.setText("Limpar ID");
        clearId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(53, 53, 53)
                            .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clearId))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idSrch_field, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(srch_btn)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(save_btn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientId_field, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Data)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(suplier_option)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(costumer_option))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(date_field)
                                        .addComponent(tValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idSrch_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srch_btn))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data)
                    .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tValue_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suplier_option)
                    .addComponent(costumer_option)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clientId_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save_btn)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void date_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_fieldActionPerformed
        
    }//GEN-LAST:event_date_fieldActionPerformed

    private void clearIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearIdActionPerformed
        idSrch_field.setText("");
    }//GEN-LAST:event_clearIdActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        if (id_field.getText().isBlank()) {
            addNF();
        } else {
            updateNF();
        }
        
        clearForm();
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NfScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearId;
    private javax.swing.JTextField clientId_field;
    private javax.swing.JRadioButton costumer_option;
    private javax.swing.JFormattedTextField date_field;
    private javax.swing.JTextField idSrch_field;
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton srch_btn;
    private javax.swing.JRadioButton suplier_option;
    private javax.swing.JTextField tValue_field;
    // End of variables declaration//GEN-END:variables
}
